# renewal.R
#
# The shared stochastic renewal engine -- the mechanistic backbone of the playground, used for BOTH
# the source epidemic at X and every country's local epidemic (analogous to the parent repo's
# sir_core.R). One engine, so the source and the destinations are generated by exactly the same
# process and any analysis that works on one works on the other.
#
# THE PROCESS (discrete time, one day per step, multi-strain, with susceptible depletion):
#   force_{k,t} = sum_{s>=1} g(s) * I_{k, t-s}              (infectious pressure of strain k)
#   I_{k,t}     ~ Poisson( R_{k,t} * (S_{t-1}/N) * force_{k,t} )  +  seeding_{k,t}
#   S_t         = S_{t-1} - sum_k I_{k,t}                   (all strains share one susceptible pool)
# g(.) is the discretised generation interval (day-0 mass = 0). R_{k,t} is the strain's change-point
# reproduction number. `seeding` plants exogenous infections on given days -- the day-0 index case at
# the source, the variant's later introduction, and (for a country) the daily imported infections.
# Multiplying by S/N gives depletion, so epidemics PEAK and turn over -- needed for the growth-to-peak
# and healthcare-demand analyses, not just the exponential-growth phase.
#
# SIMPLIFICATIONS (each a documented extension front): one well-mixed population per location; strains
# share the susceptible pool (complete cross-immunity); the generation interval is strain- and
# time-invariant. See documentation/decisions.md.
#
# References
#   Fraser C. Estimating individual and household reproduction numbers in an emerging epidemic.
#     PLoS ONE. 2007;2(8):e758.  (the renewal / infectiousness-profile formulation)
#   Cori A, et al. Am J Epidemiol. 2013;178(9):1505-1512.  (discretised renewal)
#
# Requires: R/utils.R (step_at) sourced first.

# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
### The renewal engine ##########
# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# ---- |-simulate a multi-strain renewal epidemic in one population ----
# n_days   : length of the run (days)
# N        : population size (for susceptible depletion and prevalence-as-a-fraction)
# gi_pmf   : discretised generation interval, indexed from delay 0 (gi_pmf[1] = P(0) = 0)
# rt_list  : list of per-strain step_schedule()s (length K = number of strains)
# seeding  : n_days x K matrix of exogenous infections planted on each day (day-0 seeds, variant
#            introduction, imported infections). Rows are days, columns strains.
# stochastic: TRUE -> Poisson draws (ground truth is one stochastic realisation); FALSE -> expected
#            (deterministic) infections, useful for debugging and for a noise-free reference.
# Returns: list(incidence [n_days x K], susceptible [n_days], prevalence [n_days], prevalence_by_strain).
simulate_renewal <- function(n_days, N, gi_pmf, rt_list, seeding, stochastic = TRUE) {
  K   <- length(rt_list)
  if (is.null(dim(seeding))) seeding <- matrix(seeding, nrow = n_days, ncol = K)
  stopifnot(nrow(seeding) == n_days, ncol(seeding) == K)

  gtail  <- length(gi_pmf) - 1                        # how far back the generation interval reaches
  surv   <- .infectious_survival(gi_pmf)              # P(still infectious s days after infection), s = 0..gtail

  I  <- matrix(0, nrow = n_days, ncol = K)            # incidence by day x strain
  S  <- numeric(n_days)                               # susceptibles remaining
  S_prev <- N

  for (t in seq_len(n_days)) {
    new <- numeric(K)
    for (k in seq_len(K)) {
      # infectious pressure: convolve the strain's recent incidence with the generation interval
      force_k <- 0
      smax <- min(gtail, t - 1)
      if (smax >= 1) force_k <- sum(gi_pmf[2:(smax + 1)] * I[(t - 1):(t - smax), k])
      mu   <- step_at(rt_list[[k]], t - 1) * (S_prev / N) * force_k     # expected endogenous infections
      endo <- if (stochastic) stats::rpois(1, mu) else mu
      new[k] <- endo + seeding[t, k]                                    # + exogenous seeds / imports
    }
    # cannot infect more than the remaining susceptibles: scale down proportionally in the rare clash
    tot <- sum(new)
    if (tot > S_prev && tot > 0) new <- new * (S_prev / tot)
    I[t, ] <- new
    S[t]   <- max(S_prev - sum(new), 0)
    S_prev <- S[t]
  }

  # infectious prevalence = currently-infectious people, by convolving incidence with the survival
  # of the infectiousness profile (a lean proxy; a dedicated infectious-period epidist is an
  # extension front -- see documentation/decisions.md). Returned in COUNTS; divide by N for a fraction.
  # [REFLECTION] using the GI survival as the "still infectious" kernel ties prevalence to exactly the
  # profile that drives transmission -- neat, but it slightly overstates the infectious window (the GI
  # includes the latent period). A separate infectious-period distribution would decouple the two.
  prev_by_strain <- vapply(seq_len(K), function(k) .prevalence(I[, k], surv), numeric(n_days))
  if (is.null(dim(prev_by_strain))) prev_by_strain <- matrix(prev_by_strain, ncol = K)

  list(incidence = I, susceptible = S,
       prevalence = rowSums(prev_by_strain), prevalence_by_strain = prev_by_strain)
}

# ---- |-survival of the infectiousness profile: P(still infectious s days after infection) ----
# The generation interval g(s) is the (normalised) infectiousness profile in renewal theory, so the
# probability of still being infectious at age s is its survival function 1 - CDF. Used to turn
# incidence into a currently-infectious prevalence count.
.infectious_survival <- function(gi_pmf) {
  s <- 1 - cumsum(gi_pmf)
  pmax(s, 0)                                          # survival at age 0..length-1 (P(GI > s))
}

# ---- |-currently-infectious prevalence from an incidence series and the infectious survival ----
.prevalence <- function(incidence, surv) {
  # prevalence_t = sum_{s>=0} I_{t-s} * P(still infectious at age s)
  shift_by_delay(incidence, surv)
}
