# simulate_local.R
#
# Stage 4: the local epidemics. Each country runs its OWN stochastic renewal process (renewal.R),
# seeded day-by-day by the imported infections from Stage 3 and driven by its own country-specific
# reproduction-number trajectory. Countries differ in when they intervene (config), how many imports
# they receive (connectivity x source prevalence), and their population -- so their local waves are
# heterogeneous but generated by the identical mechanism as the source. When the variant is active,
# the imported variant infections seed a second local strain that competes with the wild type in the
# shared local susceptible pool -- which is what lets the variant rise to dominance locally.
#
# Returns the LATENT truth for every country: local infections by day, country and strain.
#
# Requires: R/renewal.R, R/utils.R sourced first.

# ---- |-simulate every country's local epidemic, seeded by imports ----
# cfg : config; par : draw_parameters(cfg); imports : simulate_importations()$imports (n x c x K).
# Uses the current RNG state.
simulate_local <- function(cfg, par, imports) {
  n  <- cfg$n_days
  cc <- cfg$countries
  K  <- par$n_strains
  gi <- par$pmf$gi

  infections <- array(0, dim = c(n, length(cc), K), dimnames = list(NULL, cc, NULL))
  susceptible <- matrix(0, nrow = n, ncol = length(cc), dimnames = list(NULL, cc))

  for (j in seq_along(cc)) {
    country <- cc[j]
    N_c <- par$country_pop[[country]]

    # per-strain R: the variant inherits the country's R trajectory scaled by (1 + fitness)
    rt_list <- list(cfg$rt_country[[country]])
    if (K == 2L) rt_list[[2]] <- scale_rt_for_variant(cfg$rt_country[[country]], cfg$variant$fitness)

    seeding <- matrix(imports[, j, ], nrow = n, ncol = K)          # daily imported infections by strain
    sim <- simulate_renewal(n, N_c, gi, rt_list, seeding, stochastic = TRUE,
                            dispersion = cfg$dispersion_k %||% Inf)

    infections[, j, ] <- sim$incidence
    susceptible[, j]  <- sim$susceptible
  }

  list(infections = infections,                                    # n x n_countries x K (LATENT)
       infections_total = apply(infections, c(1, 2), sum),         # n x n_countries
       susceptible = susceptible)
}
